import { AnalysisResult } from './types';

export const SCREENSHOT_EXAMPLE: AnalysisResult = {
  score: 60,
  riskLevel: 'high',
  riskTitle: 'Высокий риск',
  statusHeading: 'Пример: новый аккаунт',
  summary:
    'Оценка высокая в основном из-за сочетания признаков: аккаунт совсем свежий, при этом статистика необычно сильная для такого количества часов, и у части друзей есть баны. Ни один признак сам по себе ничего не доказывает. Хорошо то, что на аккаунте самом нет VAC-банов. Это оценка по косвенным данным, а не доказательство читерства.',
  factors: [
    { points: 15, text: 'Аккаунту меньше месяца (18 дн.)', category: 'age' },
    { points: 20, text: 'Мало часов (74), но K/D 2.1', category: 'stats' },
    { points: 10, text: 'Очень высокий HS%: 72%', category: 'stats' },
    { points: 10, text: 'У 3 из 40 друзей есть баны', category: 'friends' },
    { points: 5, text: 'Профиль закрыт, данных для оценки меньше', category: 'privacy' },
  ],
  profile: {
    steamId: '76561199548291034',
    personaname: 'Shadow_Strike',
    avatarfull: 'https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg',
    profileurl: 'https://steamcommunity.com/profiles/76561199548291034',
    communityvisibilitystate: 1, // private
    accountAgeDays: 18,
    accountAgeYears: 0.05,
    vacBanned: false,
    numberOfVACBans: 0,
    numberOfGameBans: 0,
    daysSinceLastBan: 0,
    economyBan: 'none',
    cs2PlaytimeHours: 74,
    cs2Playtime2WeeksHours: 42,
    friendsCount: 40,
    friendsWithBansCount: 3,
    friendsChecked: 40,
  },
  manualStats: {
    kd: 2.1,
    hs: 72,
    matches: 48,
    winrate: 68,
  },
  csstats: {
    available: true,
    source: 'csstats',
    kd: 2.1,
    hs: 72,
    winrate: 68,
    matches: 48,
    rating: 1.34,
    banned: false,
    url: 'https://csstats.gg/player/76561199548291034',
    message: 'Данные получены с CSStats.gg',
  },
  timestamp: Date.now(),
};

export const VETERAN_EXAMPLE: AnalysisResult = {
  score: 8,
  riskLevel: 'low',
  riskTitle: 'Низкий риск',
  statusHeading: 'Пример: ветеранский профиль',
  summary:
    'Аккаунт выглядит максимально надёжно: солидный возраст более 8 лет, свыше 3400 часов в CS, отсутствие банов как у владельца, так и у его окружения. Статистика находится в реалистичных пределах для опытного игрока.',
  factors: [
    { points: -10, text: 'Возраст аккаунта более 8 лет (3100 дн.)', category: 'age' },
    { points: -5, text: 'Большой наигрыш в CS2 (3420 ч)', category: 'stats' },
    { points: 0, text: 'Профиль полностью открыт для проверки', category: 'privacy' },
    { points: 0, text: '0 банов среди друзей', category: 'friends' },
  ],
  profile: {
    steamId: '76561198012345678',
    personaname: 'phoenix_legend',
    avatarfull: 'https://avatars.steamstatic.com/c5d3df43a85b54fa315f484ca78772a80f0896fa_full.jpg',
    profileurl: 'https://steamcommunity.com/id/phoenix_legend',
    communityvisibilitystate: 3,
    accountAgeDays: 3100,
    accountAgeYears: 8.5,
    vacBanned: false,
    numberOfVACBans: 0,
    numberOfGameBans: 0,
    daysSinceLastBan: 0,
    economyBan: 'none',
    cs2PlaytimeHours: 3420,
    cs2Playtime2WeeksHours: 28,
    friendsCount: 120,
    friendsWithBansCount: 0,
    friendsChecked: 50,
  },
  manualStats: {
    kd: 1.15,
    hs: 48,
    matches: 1250,
    winrate: 54,
  },
  timestamp: Date.now(),
};

export const BANNED_EXAMPLE: AnalysisResult = {
  score: 95,
  riskLevel: 'high',
  riskTitle: 'Критический риск',
  statusHeading: 'Пример: забаненный профиль',
  summary:
    'На аккаунте зафиксирован активный VAC-бан или блокировка патруля/игры. В сочетании с аномальными показателями попаданий в голову это однозначно указывает на историю нечестной игры.',
  factors: [
    { points: 50, text: 'Зафиксирован активный VAC/Game бан', category: 'bans' },
    { points: 20, text: 'Экстремальный показатель HS%: 88%', category: 'stats' },
    { points: 15, text: 'K/D 3.4 при 110 часах в игре', category: 'stats' },
    { points: 10, text: 'У 7 друзей в профиле есть баны', category: 'friends' },
  ],
  profile: {
    steamId: '76561198998877665',
    personaname: 'SpinToWin_CS',
    avatarfull: 'https://avatars.steamstatic.com/0000000000000000000000000000000000000000_full.jpg',
    profileurl: 'https://steamcommunity.com/profiles/76561198998877665',
    communityvisibilitystate: 3,
    accountAgeDays: 95,
    accountAgeYears: 0.26,
    vacBanned: true,
    numberOfVACBans: 1,
    numberOfGameBans: 1,
    daysSinceLastBan: 14,
    economyBan: 'banned',
    cs2PlaytimeHours: 110,
    cs2Playtime2WeeksHours: 5,
    friendsCount: 28,
    friendsWithBansCount: 7,
    friendsChecked: 28,
  },
  manualStats: {
    kd: 3.4,
    hs: 88,
    matches: 52,
    winrate: 89,
  },
  timestamp: Date.now(),
};
